### ISSUE TITLE
Add styling to .pagination

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/plonetheme.barceloneta#103]
For Plone 5.0.3.1
With change from .listingBar to .pagnation, need to add horizontal styling. Add at a minimum (for horizontal list):
```
.pagination ul {
    list-style: outside none none;
}

.pagination li {
    display: inline;
}
```
Add spacing to make it look nicer: 
```
.pagination ul {
    display: inline-block;
    list-style: outside none none;
    margin: 20px 0;
    padding: 0;
}

.pagination li {
    display: inline;
}

.pagination .next {
        float: right;
        margin-left: 20px;
    }
    
.pagination .previous {
        margin-right: 15px;
    }
```

**Comment by davilima6** [comment]
@3dogMcNeill if you need more help with this you can ping me in Plone's Slack. Are you there yet? http://slackin-toplone.rhcloud.com/

**Comment by 3dogMcNeill** [comment]
it's going to take me a long time to figure this out. If somebody can fix this in the meantime, please don't wait on me.

**Comment by davilima6** [comment]
@3dogMcNeill I'm offering to guide you so that we decrease that time and also you feel confident making many important contributions (like this) in the short future. Do you have Slack installed? Join #Plone :)

**Comment by 3dogMcNeill** [comment]
Turns out [this was resolved in Jan](https://github.com/plone/plonetheme.barceloneta/commit/62de9a7e8bde2d605a08b0e00cb3e053bb96220b)
