### ISSUE TITLE
Level 3 indentation in sitemap in Plone 5 wasn't display nicely

### ISSUE THREAD

**Issue by ivanteoh** [plone/plonetheme.barceloneta#106]
Tested with plonetheme.barceloneta 1.6.18, level 3 indentation in sitemap wasn't display nicely.

<img width="1413" alt="sitemap_plone5" src="https://cloud.githubusercontent.com/assets/900434/14945833/3b6ce8fc-105c-11e6-88ca-0d8ecbfeddac.png">

**Comment by davilima6** [comment]
Couldn't reproduce in Chrome, same Barceloneta version (Plone 5.0.4).

![screenshot-plone5ux herokuapp com 2016-05-03 06-48-19](https://cloud.githubusercontent.com/assets/422130/14979821/17a267f4-10fb-11e6-95d7-34ecbe3d3703.png)

For some reason you seem to have an extra `display: inline` (or `float: left`) in your 2nd level links, could you please check which file is this coming from?

**Comment by ivanteoh** [comment]
I couldn't find any other css that add extra `display: inline` (or `float: left`). But it works fine after I removed all other plugins and left only Plone 5 and barceloneta theme. I guess it is a false alarm. Close this issue for now.
