### ISSUE TITLE
Set background color on lead image of a newsitem

### ISSUE THREAD

**Issue by staeff** [plone/plonetheme.barceloneta#107]
If the lead image of an newsitem is transparent, there is a visual conflict with the line that belongs to the title of the newsitem. Setting the background of the image to `@plone-body-bg` makes it look better.

a) before 
<img width="887" alt="newsleadimage-before" src="https://cloud.githubusercontent.com/assets/464145/15291964/042302b6-1b81-11e6-823e-07339a437912.png">

b) after
<img width="880" alt="newsleadimage-after" src="https://cloud.githubusercontent.com/assets/464145/15291991/12ae752c-1b81-11e6-8858-3fcc3c045da3.png">

I saw this problem here: https://plone.org/news/2016/plone-selected-for-2016-google-summer-of-code (This is the plone.org - theme, but barceloneta shows the same behaviour)

**Comment by fgrcon** [comment]
see  also discussion at end of https://github.com/plone/plone.app.contenttypes/issues/298

**Comment by staeff** [comment]
@fgrcon Thanks for the hint. I was not aware of this discussion.
