### ISSUE TITLE
Icons in tool bar when no link is there

### ISSUE THREAD

**Issue by keul** [plone/plonetheme.barceloneta#110]
When an item in the toolbar has no link but is only static text + icon (in the example: a not alterable workflow state) the item is show with a different and not likable intentation.

![schermata 2016-06-15 alle 11 09 00](https://cloud.githubusercontent.com/assets/284924/16178487/9ce2a21c-3649-11e6-9c90-6510b7263c2e.png)

**Comment by enkidulan** [comment]
I've added fix for this issue https://github.com/enkidulan/plonetheme.barceloneta/commit/0a6914d3a3814f3d262c24104ffea1ab95260cce and will create PR shortly.

**Comment by vincentfretin** [comment]
This is still an issue in Plone 5.2.2rc1, I tested by moving all span out of the a tag and removing the a tag via the DOM inspector.
![Capture d’écran de 2020-06-30 08-54-51](https://user-images.githubusercontent.com/112249/86093534-6719ab00-baaf-11ea-95f2-0f127d090fd8.png)

The fix should be a css fix, not an additional diazo rule.

**Comment by vincentfretin** [comment]
@enkidulan I made a similar fix than yours at the template level https://github.com/plone/plone.app.contentmenu/pull/29
