### ISSUE TITLE
Remove 100% width from select?

### ISSUE THREAD

**Issue by agitator** [plone/plonetheme.barceloneta#118]
https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/forms.plone.less#L91

Was there an actual reason to style select elements width 100% width and display block?
I think it's really annoying and would reset it to width: unset; and display: inline-block;.

opinions?

@plone/usability-team 

![screen shot 2016-11-01 at 11 37 00](https://cloud.githubusercontent.com/assets/365761/19887310/fa266344-a027-11e6-8985-6ad59e41be43.png)
![screen shot 2016-11-01 at 11 36 40](https://cloud.githubusercontent.com/assets/365761/19887311/fa280348-a027-11e6-9c69-fa2100b337db.png)

**Comment by davilima6** [comment]
+1. But maybe we could leave those settings for mobile only, since usability is usually worse for <select> on smaller/touch devices.

**Comment by agitator** [comment]
not sure where the advantage of a 100% width for mobile is, the selection opens in a separate drawer on mobile anyway

**Comment by davilima6** [comment]
It's a pattern made popular by jQuery Mobile and Bootstrap. The advantage is the increase in the touch target area before the native drawer is invoked. For instance, imagine a `<select>` with short sized options, like numbers. Also imo it makes for a more homogeneous UI when screen estate is reduced.

**Comment by agitator** [comment]
I haven't seen any form elements that are too tiny with barceloneta on mobile, but feel free to add them where needed  ;-)
