### ISSUE TITLE
Remove margin-top from heading styles

### ISSUE THREAD

**Issue by agitator** [plone/plonetheme.barceloneta#122]
```

//*// Headings
h1, h2, h3, h4, h5, h6 {
  font-family: @plone-headings-font-family;
  font-weight: @plone-headings-font-weight;
  line-height: @plone-headings-line-height;
  color: @plone-headings-color;
}

h1, h2, h3 {
  margin-top: @plone-line-height-computed;
  margin-bottom: (@plone-line-height-computed / 2);
  a:hover, a:focus { text-decoration: none; border-bottom: 2px @plone-link-hover-color solid; }
}
h4, h5, h6 {
  margin-top: (@plone-line-height-computed / 2);
  margin-bottom: (@plone-line-height-computed / 2);
}

```

The margin-top definitions on heading style are quite annoying if you want to align items horizontally reasonable. They also make styling of mosaic tiles more annoying than necessary.

margin-top should only be put in place where the context needs it.

@plone/usability-team opinions?

**Comment by tkimnguyen** [comment]
No opinion... assuming this change does not break anything :)

**Comment by agitator** [comment]
leave it like it is, the implications are too big...
also user-agent styles also include some margin-top by default
