### ISSUE TITLE
Vertical align of nav items thumbs in navigation portlet is off

### ISSUE THREAD

**Issue by enkidulan** [plone/plonetheme.barceloneta#137]
See the screen shot:
 
![screenshot_20170724_132800](https://user-images.githubusercontent.com/963412/28525561-55d7abc2-708d-11e7-960d-99ed581502ff.png)

Plone version: 5.0.7
plone.app.portlets: 3.1.5
plonetheme.barceloneta: 1.6.23
The build I've used is: https://github.com/plone/simple-plone-buildout/tree/5.0.7-with-docs

**Comment by thet** [comment]
Fixed with: https://github.com/plone/plonetheme.barceloneta/pull/138
