### ISSUE TITLE
Markup is broken when printing page

### ISSUE THREAD

**Issue by enkidulan** [plone/plonetheme.barceloneta#139]
![print_page](https://user-images.githubusercontent.com/963412/28613251-8abc9564-71fa-11e7-942f-7491c034aab3.jpeg)

Plone version: 5.0.7
plonetheme.barceloneta: 1.6.23
The build I've used is: https://github.com/plone/simple-plone-buildout/tree/5.0.7-with-docs

**Comment by thet** [comment]
Closed with: https://github.com/plone/plonetheme.barceloneta/pull/140
