### ISSUE TITLE
Live searchbox shows with scroll bars on Users/Groups panel

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plonetheme.barceloneta#154]
On the Users and Groups control panel, both the Users tab and the Groups tab, the live searchbox needlessly shows with scroll bars:

![screen shot 2018-05-22 at 12 24 05](https://user-images.githubusercontent.com/210587/40357030-38919dfe-5dbb-11e8-888b-3112105cab92.png)

This is caused by commit d006020a5e77fb7151ea4f754f4932546aa0ea52, which has been there since Plone 5.0.0, and is still there in 5.1.2 (or current coredev 5.0 and 5.1).
Best solution is probably to make the css identifier more specific: only set the overflow on forms within the id `content-core`.

Additionally, this may be useful, to make the remaining users/groups form prettier:
- Set `overflow` to `auto`, because currently the scroll bars show even when no scroll bar is needed.
- Only set `overflow-x`, because I don't think we mind that the list is long vertically. We only care about the horizontal overflow, because it may disappear behind a portlet (https://github.com/plone/Products.CMFPlone/issues/879).

**Comment by vincentfretin** [comment]
Actually it's worse, look at the livesearch in Plone 5.2.2rc1
![Capture d’écran de 2020-06-30 08-57-51](https://user-images.githubusercontent.com/112249/86093842-e5764d00-baaf-11ea-8938-d918f7dbcc44.png)

**Comment by vincentfretin** [comment]
Same issue on the Add new user modal.
![Capture d’écran de 2020-07-02 13-42-59](https://user-images.githubusercontent.com/112249/86354799-f965ae80-bc69-11ea-83fe-05b6db2360b2.png)
