### ISSUE TITLE
Fresh Installed Plone 5.1 From Source does not Compile CSS

### ISSUE THREAD

**Issue by ghost** [plone/plonetheme.barceloneta#157]
I have fresh install from Plone 5.1 Source with included barceloneta Thema. Did this job on three independent Systems (Mac OS High Sierra, Ubuntu Virtual Box Image, Ubuntu Live-System).

Alle Three System are not able to simple Change a Color in /less/variables.plone.less an compile the theme after copying the complete theme.

Overriting the Variable @plone-link-color with resource Registration in Debug Mode works fine, but Compiling Changes with Ressource Panel crashes the complete Theme.

Environment on Mac is:
Plone 5.1.2.1 (5112)
CMF 2.2.12
Zope 2.13.27
Python 2.7.10
PIL 5.1.0

Other Themes Compile Less with integrated Editor without issue.

Sincerly
Thorsten

**Comment by gforcada** [comment]
For Plone 6 the whole bundling has changed completely, you might want to have a look at it again 😄
