### ISSUE TITLE
@@manage-viewlets View is unuseable

### ISSUE THREAD

**Issue by tomgross** [plone/plonetheme.barceloneta#16]
With Plone 5.0b1 the manage-viewlets View is unuseable. Some of the occurences:

- Viewlet information in toolbar is not viewable / accessible
- Buttons and links (Show/Hide/up/down) have no effect

**Comment by Martronic-SA** [comment]
It seems not to be working even if you disable theming. There for is taht really related to the barceloneta theme?

**Comment by tomgross** [comment]
Ok. Let's use this: https://github.com/plone/Products.CMFPlone/issues/782
