### ISSUE TITLE
Can Not Login on Mobile Screen?

### ISSUE THREAD

**Issue by l34marr** [plone/plonetheme.barceloneta#17]
![mobile-phone-screen](https://cloud.githubusercontent.com/assets/56113/7314140/e9f0d9c8-ea93-11e4-8146-ca49cae4ac3d.png)

This is what I see from my mobile phone screen. Can not find a way to click on Log in.

**Comment by tkimnguyen** [comment]
@l34marr which phone model is this?

**Comment by vangheem** [comment]
this was fixed by @agitator for b3.

**Comment by l34marr** [comment]
@tkimnguyen the issue is fixed as @vangheem says. But, when clicking to login, the right edge of the overlay is a little bit outside the screen. Anyway, not big issue. My mobile phone is Mi 2s.
![plone-screen1](https://cloud.githubusercontent.com/assets/56113/8954283/1e2b0406-3617-11e5-8aa1-3ad2b4a24768.png)
![plone-screen2](https://cloud.githubusercontent.com/assets/56113/8954294/2cfc65e2-3617-11e5-8905-8ce1617fc7a3.png)

**Comment by agitator** [comment]
then "someone" has to add extra responsive styles ... fixed only the basic appearance for smaller widths
