### ISSUE TITLE
Toolbar items without an icon are invisible until you hover on them

### ISSUE THREAD

**Issue by keul** [plone/plonetheme.barceloneta#19]
Don't know if is an issue for the theme or plone.app.toolbar, in that case I'll reopen somewhere else.

When an item (I mean "actions" on old Plone) has no CSS icon attached, the text that normally is displayed when hovering on the item is not shown, or better is show when you over on the invisible button.

![schermata 05-2457144 alle 16 47 01](https://cloud.githubusercontent.com/assets/284924/7431727/c993d5ac-f021-11e4-8f6b-adf596fd8cfe.png)
![schermata 05-2457144 alle 16 47 24](https://cloud.githubusercontent.com/assets/284924/7431728/c99bcfdc-f021-11e4-9197-3854d406f0dc.png)

**Comment by Abhii67534** [comment]
Please assign this issue to me

**Comment by gforcada** [comment]
I think we can close this already 😄
