### ISSUE TITLE
arrow in menu and livesearch checkbox not vertically aligned

### ISSUE THREAD

**Issue by vincentfretin** [plone/plonetheme.barceloneta#202]
In Plone 5.2.2 / plonetheme.barceloneta 2.1.7
the arrow in menu and livesearch checkbox are not vertically aligned.

Chrome + Ubuntu 18.04
![Capture d’écran de 2020-07-01 15-56-17](https://user-images.githubusercontent.com/112249/86253274-9b2ac400-bbb4-11ea-9227-d85ee9942355.png)

For the checkbox in livesearch, I'm wondering if it's not OS specific.
I'm on Ubuntu 18.04. What do you folks have? Can you please share a screenshot in macOS or Windows? @ale-rt ?

Better looking should be:
![Capture d’écran de 2020-07-01 16-09-09](https://user-images.githubusercontent.com/112249/86253759-3cb21580-bbb5-11ea-9c40-d2e0adfa0e80.png)

Do you agree?

```
input[type="radio"], input[type="checkbox"] {
￼    /* margin: 4px 0 0;*/
}

@media (min-width: 768px) {
.plone-nav li label:after {
￼    padding: 0.75em 1em 0em 0; // instead of 0.5em 1em 0.5em 0
}
}
```

**Comment by vincentfretin** [comment]
Ha ha, commenting the checkbox rule to fix the livesearch checkbox changed the checkbox in resources registry, now its not aligned anymore. :-)

**Comment by ale-rt** [comment]
Chrome + Ubuntu 20.04
![image](https://user-images.githubusercontent.com/1300763/86254622-5d2e9f80-bbb6-11ea-8eef-e09668970e44.png)
Firefox + Ubuntu 20.04
![image](https://user-images.githubusercontent.com/1300763/86254660-6cade880-bbb6-11ea-970d-7bc99135b2bb.png)
The arrow looks slightly better aligned with FF, but the check box is broken in both.
I agree with removing the checkbox margin maybe `.searchSection` to make it specific.

**Comment by vincentfretin** [comment]
Ha ha, why do have a smaller arrow in FF Ubuntu 20.04? :)
My previous screenshot was on Chrome Ubuntu 18.04.

Chrome + Ubuntu 18.04
![Capture d’écran de 2020-07-01 16-48-51](https://user-images.githubusercontent.com/112249/86258281-efd13d80-bbba-11ea-9af4-e8aaa1612797.png)

Firefox + Ubuntu 18.04
![Capture d’écran de 2020-07-01 16-49-21](https://user-images.githubusercontent.com/112249/86258295-f495f180-bbba-11ea-9d07-24ac10f13ea1.png)
The arrow alignment seems perfect on this one.

**Comment by vincentfretin** [comment]
In PR #206 the commit https://github.com/plone/plonetheme.barceloneta/pull/206/commits/0a2e35b483293a1619e22d73aedb1c2fabde8921 fix the issue for the search checkbox with `vertical-align: middle` on the label.
![Capture d’écran de 2020-07-07 17-23-25](https://user-images.githubusercontent.com/112249/86803789-99f70c80-c076-11ea-8819-ca18d1fbf4b9.png)

**Comment by vincentfretin** [comment]
I gave up for the arrow, it will stay like this.
