### ISSUE TITLE
active form tabs should not have a bottom border

### ISSUE THREAD

**Issue by petri** [plone/plonetheme.barceloneta#210]
(This is for the 2.x LESS-based version. Seems to be fixed in master SCSS)

See image; here the `Resource Types` is the chosen tab yet it has a bottom border, making it impossible to distinguish which is active tab.

<img width="1176" alt="Näyttökuva 2020-8-6 kello 18 19 46" src="https://user-images.githubusercontent.com/64672/89550311-26315680-d812-11ea-93a8-358c29dc5153.png">

Could be fixed by adding `!important` here:

https://github.com/plone/plonetheme.barceloneta/blob/2.x/plonetheme/barceloneta/theme/less/formtabbing.plone.less#L32

**EDIT: that seems to be not enough; turning the line into `border-bottom: 1px solid @plone-portlet-content-bg ~'!important';` seems to work better.**

**Comment by vincentfretin** [comment]
The border-bottom comes from `#content-core a`
I see there are already rules to override this for the resource registry control panel tabs in `plonetheme/barceloneta/theme/less/main.plone.less`
```
 #content-core .pat-structure a, #content-core .pat-resourceregistry a {         
    border-bottom: none;                                                          
  }                                                                               
  #content-core .pat-structure a.btn, #content-core .pat-resourceregistry  a.btn, #content-core .pat-structure .pagination a { 
    border-bottom: 1px solid @plone-gray-lighter;                                 
  }
```
You may want to do a similar fix.

**Comment by petri** [comment]
Thanks @vincentfretin - I guess having a specific rule would be indeed preferable to littering the place with `!important` ...
