### ISSUE TITLE
Update markup of templates to Bootstrap 5

### ISSUE THREAD

**Issue by santonelli** [plone/plonetheme.barceloneta#225]
Due to #2967 we have to update icons and markup of the templates listed below. Feel free to add missing templates here.

**Comment by santonelli** [comment]
I try to reflect the current state. Please add comments or add information if i miss something.

What happened?

- LESS has been converted to SASS
- Bundeling story is now yarn based (package.json)

Todos

- Cleanup (unused stuff in SCSS)
- Remove LESS artifacts
- Remove unused SCSS variables
- Update preview image
- Update docs

Questions

- Why is SCSS in package root?

**Comment by agitator** [comment]
theme specific todos in https://github.com/plone/Products.CMFPlone/issues/3061
