### ISSUE TITLE
Folder_contents icons missing

### ISSUE THREAD

**Issue by Gomez** [plone/plonetheme.barceloneta#230]
https://demo.plone.org/de/folder_contents
![2021-02-21_18-36](https://user-images.githubusercontent.com/48724/108633294-cd56a200-7473-11eb-894d-7ac4aeebba8e.png)

https://demo-latest-plone6.plone.org
![2021-02-21_18-35](https://user-images.githubusercontent.com/48724/108633265-9d0f0380-7473-11eb-89ea-8d9ebc1a98e4.png)

contents.plone.less is not migrated to scss.

**Comment by agitator** [comment]
@Gomez will be fixed in mockup es6

**Comment by MrTango** [comment]
you can try the es6 plipfile, but it's not ready for production. Some stuff is not styled perfectly, but most patterns are working already.

**Comment by MrTango** [comment]
It runs already without requireJS, the resource registry control panel is useless right now, but you can set the development mode for resources thrue the config registry, in case you want to develop on the patterns or css in general. Have a look at the package.json scripts for commands. The one with plone in the name copy the compiled resources into the plone.staticresources, there is also a what command doing the same.

**Comment by petschki** [comment]
fixed here https://github.com/plone/mockup/commit/3bcced114a27fe636606dd2f1fd145689c3398fb
