### ISSUE TITLE
Should we use modern svg files for country flags?

### ISSUE THREAD

**Issue by 1letter** [plone/plonetheme.barceloneta#233]
or is this a question for plone.i18n / plone.app.multilingual / Products.CMFPlone package?

**Comment by agitator** [comment]
Yes we should ;-)
The flags are in plone.i18n and the logic as well plone/i18n/locales/countries.py
@1letter can you open an issue in plone.i18n?

**Comment by 1letter** [comment]
Yes i will do that.
