### ISSUE TITLE
lead image and folder listing

### ISSUE THREAD

**Issue by yurj** [plone/plonetheme.barceloneta#257]
Hi!

 if we enable the lead image behaviour, the folder listing uses float-end to show the images but if there are more than one after another, they overlaps:

![leadimage](https://user-images.githubusercontent.com/1100944/140884640-b4a615cc-00af-493d-9715-152437be1db2.png)

I would just use the margin-auto trick with flex to have the image positioned on right:

![me-auto](https://user-images.githubusercontent.com/1100944/140885837-eba3d760-470c-4734-8b27-a36311f4a3e2.png)

using this code:

```
<div class="mb-1 d-flex"> <- add d-flex here
                        <a href="/test-immagine" title="Folder" class="contenttype-folder state-published url">test immagine</a>
                        <a href="/test-immagine" class="ms-auto"> <- add ms-auto here
                          <img src="/test-immagine/@@images/e6bc132c-51da-4bdf-beba-0362b36c3fc9.jpeg" alt="test immagine" title="test immagine" class="thumb-thumb" width="128" height="98"> <- here remove float-end class
                        </a>
                      </div>
```

if the lead image/image field is the only displayed. Looking at the listing template it should because other info (event, byline) are in the next row. The logged version has too much space:

![lead_image_logged_in](https://user-images.githubusercontent.com/1100944/140887133-9d65d0e1-9048-41b0-9a2c-1f6f74006d13.png)

so maybe this is not the best solution. Another solution can be just to add a min-height when there's an image:

`<article class="mb-3" tal:attributes="style python: 'min-height: 98px' if item_has_image and thumb_scale_list else ''">`
(replace 98px with the thumb height)

![min-width-float-end](https://user-images.githubusercontent.com/1100944/140889873-f09fe656-0b9e-40d4-9fe3-43be3b50d67d.png)

**Comment by petschki** [comment]
Fixed here https://github.com/plone/plone.app.contenttypes/commit/78b5a7d4148506380bc3e65b7bd67ea2eb2170f8 since `plone.app.contenttypes=3.0.0a11`

**Comment by Rudd-O** [comment]
So nice.  Thanks
