### ISSUE TITLE
table styles are on legacy?

### ISSUE THREAD

**Issue by yurj** [plone/plonetheme.barceloneta#259]
To reproduce, add a table in tinymce with some style (grid for example), no style is applied. The tables definitions are in legacy:

https://github.com/plone/plonetheme.barceloneta/blob/ee8f56a54438699972196d3ff40fb59a00e885e9/scss/legacy/tables.plone.scss

**Comment by petschki** [comment]
legacy was removed completely ... reuse Bootstrap whenever possible
