### ISSUE TITLE
How to make your changes visible?

### ISSUE THREAD

**Issue by gforcada** [plone/plonetheme.barceloneta#26]
I was working on https://github.com/plone/Products.CMFPlone/issues/572 and decided to remove ``#portal-colophon`` from https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/footer.plone.less#L63

But after having change that, no matter how many times I reload the page, the text is still uppercase.

Creating a new Plone site does not help either.

I tried looking at the resource ``@@resourceregistry-controlpanel`` but I couldn't see any button that was about recompiling the theme CSS files...

**Comment by vangheem** [comment]
The build button does CSS and JavaScript

**Comment by vangheem** [comment]
Oh wait, I see what you're saying. You're working on that package.

You need to run grunt. Take a look at: https://github.com/plone/plonetheme.barceloneta/blob/master/HOWTO_DEVELOP.txt

**Comment by gforcada** [comment]
Thanks, I was also missing adding plonetheme.barceloneta to checkouts.cfg ... damn! :)
