### ISSUE TITLE
Hamburger site menu does not unfold on Plone 6

### ISSUE THREAD

**Issue by Rudd-O** [plone/plonetheme.barceloneta#260]
Latest Plone 6 alpha does not unfold the hamburger main menu (the one that shows the site sections) on mobile when tapping it.  Works on desktop.  On Android, nothing happens -- neither in Chrome nor in Fennec, not even on iPhone.

Vanilla Barceloneta shipping with Plone 6, if anyone wants to know.

The menu works fine in Plone 5.2.

We're of course talking Plone Classic, not Volto.

**Comment by Rudd-O** [comment]
Actually, it seems to be a problem with the Chrome web engine.  I can repro it in desktop by simply narrowing the window enough that the popup button appears, and then trying to click — no popup at all.

**Comment by yurj** [comment]
https://6-classic.demo.plone.org/en here I can't see the problem.
```
Plone 6.0.0a3.dev0 (6003)
CMF 2.5.4
Zope 5.4.dev0
Python 3.8.3 (default, Jul 14 2020, 07:39:54) [GCC 7.5.0]
PIL 8.3.1 (Pillow)
WSGI: On
Server: waitress 2.0.0```

Also on a local instance it is all ok. is it a plain Plone? Can you post a screenshot?

**Comment by Rudd-O** [comment]
It's worth noting that the same problem is apparent from all custom themes inheriting from Barceloneta created using the `bomtemplates3.plone` Python package.

**Comment by Rudd-O** [comment]
Hang on retrying...

**Comment by Rudd-O** [comment]
In a completely vanilla site, the button doesn't work either.  Nothing in the logs of the site either.

None of the JavaScripts are being loaded by the front page of the vanilla site.  I don't know what's up.  In my development site, they appear.  In my staging site, they don't.  What could it be?

**Comment by Rudd-O** [comment]
Well at least we know it isn't a Barceloneta problem.

**Comment by yurj** [comment]
> In a completely vanilla site, the button doesn't work either. Nothing in the logs of the site either.
> 
> None of the JavaScripts are being loaded by the front page of the vanilla site. I don't know what's up. In my development site's HTML, they appear fine. In my staging site, they don't. What could it be?

did you run npm install/ run build on the staging? You need them to create the files.

**Comment by Rudd-O** [comment]
Uh, in which directory do I have to run that to compile Plone 6 javascripts?

**Comment by yurj** [comment]
when you use plonecli, there's a nice readme with all the instructions. You've to run it in the 'theme' directory.
<https://github.com/plone/bobtemplates.plone/blob/main/bobtemplates/plone/theme_barceloneta/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/theme/README.rst.bob>

**Comment by Rudd-O** [comment]
Oh yeah I did that a buncha times, didn't fix the problem.  Just blew away the sites and started from scratch.

**Comment by Rudd-O** [comment]
Note I was mentioning the Plone Javascripts were missing, not the Barceloneta ones.

**Comment by agitator** [comment]
Toggling dev mode in the resource registry should solve it for now... the bootstrap js will be added in a different way than with a legacy bundle when the mockup es6 work is finished.

**Comment by Rudd-O** [comment]
Curiously, I tried that too, and that didn't work either.  No worries tho, I am positive something was funky about my devenv.
