### ISSUE TITLE
release npm package with barceloneta es6/toolbar

### ISSUE THREAD

**Issue by yurj** [plone/plonetheme.barceloneta#272]
Hi!
 for themes depending on barceloneta (or using components from barceloneta), a new release of the npm package is needed.

https://www.npmjs.com/package/@plone/plonetheme-barceloneta-base

To test it anyway, I just copied the scss dir over the node_modules package.

**Comment by 1letter** [comment]
@yurj a npm update is available

**Comment by agitator** [comment]
with each pypi release of the theme we do one on npm for the base package as well ;-)
