### ISSUE TITLE
increase scores in lighthouse analytics

### ISSUE THREAD

**Issue by iham** [plone/plonetheme.barceloneta#285]
the scores are pretty good on [desktops](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2F6-classic.demo.plone.org%2Fen%2Ffrontpage&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&utm_source=lh-chrome-ext):
<img width="681" alt="Screenshot 2022-05-18 at 12 29 47" src="https://user-images.githubusercontent.com/36721/169018821-2d7334b4-0db9-4f7e-8c19-bc28d1639d20.png">
 
but on [mobile](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2F6-classic.demo.plone.org%2Fen%2Ffrontpage&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&utm_source=lh-chrome-ext) there is room for improvements:
<img width="666" alt="Screenshot 2022-05-18 at 12 30 47" src="https://user-images.githubusercontent.com/36721/169018995-8e2b94fe-9843-489a-91cc-42e21930c62f.png">

what could be done:
- [ ] Make “technical details” heading in the footer an h5/6
- [ ] Better contrast in Hero Item and Footer (blue on grey and dark blue on black is too low in contrast)
- [ ] Set an explicit width and height on the logo
- [ ] remove ```aria-hidden="true"``` from global sections as there are focusable elements inside (like search input)
- [ ] fine tune css and js resources (mockup)

**Comment by yurj** [comment]
Performance are mostly related to the size of javascript/css loaded. I don't think we can break it down.

**Comment by ampsteric** [comment]
hey! , I would be happy to help.
Please assign me this issue also under hacktoberfest.

**Comment by Rudd-O** [comment]
@yurj it would definitely be worth trying.  Work on this would be phenomenal.

**Comment by petschki** [comment]
Current state:

desktop
<img width="455" alt="Bildschirm­foto 2022-11-24 um 12 15 08" src="https://user-images.githubusercontent.com/511761/203771009-df6011bd-061c-4bf0-ab68-960bd65767d4.png">

mobile
<img width="473" alt="Bildschirm­foto 2022-11-24 um 12 14 35" src="https://user-images.githubusercontent.com/511761/203771030-86f5584e-7496-40e4-a373-40ad6810e7f3.png">

**Comment by Rudd-O** [comment]
What happened to make us soooo good?  Either way this is great news.
