### ISSUE TITLE
Save Button not available

### ISSUE THREAD

**Issue by 1letter** [plone/plonetheme.barceloneta#298]
![Bildschirmfoto vom 2022-07-01 09-59-39](https://user-images.githubusercontent.com/11072000/176852085-128354bb-0f12-42bb-8dea-310800b4b8fa.png)

The save button for the filter selection is not available in folder contents view. Monitor resolution 1600x900.

**Comment by ampsteric** [comment]
hey! , I would be happy to help.
Please assign me this issue also under hacktoberfest.

**Comment by petschki** [comment]
Still an issue? I could not reproduce this on https://6-classic.demo.plone.org/en/folder_contents ... I think this has been solved in Bootstrap. If the Screen is smaller than the dropdown and you scroll down, first the main window is scrolled to the end and after that the dropdown scrolls to the end:


https://user-images.githubusercontent.com/511761/203769279-880ef13e-0ac7-442d-b4a8-e55c8216ed5b.mov

**Comment by yurj** [comment]
I confirm, the bug has been solved time ago, at least in alpha2.

**Comment by 1letter** [comment]
Yes, i can confirm that this issue is go away.
