### ISSUE TITLE
Broken CSS compile in 3.0.0b3 (tinymce-formats.css)

### ISSUE THREAD

**Issue by Rudd-O** [plone/plonetheme.barceloneta#305]
Barceloneta.scss includes

```
36 │ @import "../plonetheme/barceloneta/theme/tinymce/tinymce-formats";
```

This thing somehow did NOT ship with the NPM release (it is not there after an `npm update`).

What is up with that, folks?

**Comment by mauritsvanrees** [comment]
This was fixed by @MrTango in beta 5 (beta 4 was a mistake by me). Can you check please?

**Comment by Rudd-O** [comment]
Will check.

**Comment by Rudd-O** [comment]
Got fixed indeed.  Thanks.
