### ISSUE TITLE
Odd behavior with TinyMCE — insert link, then the modal backdrop remains

### ISSUE THREAD

**Issue by Rudd-O** [plone/plonetheme.barceloneta#310]
I'm using the latest beta Barceloneta, and I've noticed that when I add a link using TinyMCE's add link button, after hitting OK, the modal backdrop persists and I can only continue editing the content item if I use the Web inspector to remove the modal backdrop `div`.

This happens on Firefox desktop.

**Comment by petschki** [comment]
Is this still the case? Could you please test this on 6-classic.demo.plone.org ?

**Comment by Rudd-O** [comment]
Nope, I don't see that problem there.  Please don't close the ticket — let's start a dialog here.  I am running the beta 3 Plone from the container release.  What version Plone is the demo site using?

**Comment by petschki** [comment]
It uses `buildout.coredev` versions and checkouts. There's also a new 6.0.0rc1 release out. Should be fixed with that.

**Comment by Rudd-O** [comment]
OK got the container.  Reporting that RC3 with both my custom theme AND Barceloneta-as-shipped has this problem too.

Requesting next steps to debug this issue, because Plone 6 should not go to GA with it.

**Comment by Rudd-O** [comment]
Excellent news.  I have discovered that the problem was a Firefox extension called Autoscrolling.  I killed it, and now everything works perfectly.

I did this after running locally from buildout and experiencing the same issue no matter what combo of eggs and options I tried.  Sigh.
