### ISSUE TITLE
TinyMCE Insert Image dialog on mobile device needs tweaking

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plonetheme.barceloneta#32]
Apologies if this isn't the correct repo to report this in!

The following is on an iPhone 6 Plus:

- When you click the Insert Image toolbar icon, the dialog at first doesn't show up; it appears to be a black screen until you scroll to the top of the screen.
- In "Drag and drop files from your desktop" could we change "desktop" to "device" or "computer"?
- The "Drop files here" area and the "Browse" and "Upload" buttons are cropped
- Change "Just drag N drop" -> "Drag and drop"
- The error "You are not authorized to add content to this folder" is cropped and isn't very obvious visually. It's also not clear what I can do about it (do I cancel out and give up editing this item?).
- It's not clear what to do after you Browsed and selected an image... I figured out I had to scroll down to click the "Upload" button
- Once I'm done uploading the image, do I have to click the Insert button at the very bottom?

@plone/ux-team

**Comment by vangheem** [comment]
Needs to be in CMFPlone. Not much to do with the theme.

**Comment by tkimnguyen** [comment]
moved to https://github.com/plone/Products.CMFPlone/issues/762
