### ISSUE TITLE
NPM release of 3.1.0

### ISSUE THREAD

**Issue by rnixx** [plone/plonetheme.barceloneta#323]
Can we have a NPM release of 3.1.0 please?

**Comment by mauritsvanrees** [comment]
@thet You have created the PyPI release of 3.1.0, so can you create the npm release as well?  See https://github.com/plone/plonetheme.barceloneta/blob/master/NPM_RELEASE.rst but you probably know better than I how to do that. :-)

If you don't have access to npm for this package, either @petschki or I can release it too.

**Comment by petschki** [comment]
there already is one: https://www.npmjs.com/package/@plone/plonetheme-barceloneta-base/v/3.1.0-alpha.0
I've done that last week.

**Comment by rnixx** [comment]
@lenadax ^^

@petschki Thank you
