### ISSUE TITLE
Creating new theme based on Barceloneta fails

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plonetheme.barceloneta#335]
I wanted to update a custom theme to latest Barceloneta, but I get an error:

```
Error: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
```

So let's start from scratch, following the [training docs for a new theme](https://training.plone.org/theming/preparation.html):

```
# Accept default answers here, except that we want Plone 6.0.5:
$ plonecli create addon plonetheme.tester
$ cd plonetheme.tester
```

We could add [new versions for Classic UI packages](https://github.com/plone/buildout.coredev/pull/864/files), but let's ignore the Python side for now, and concentrate on the theme with npm:

```
$ plonecli add theme_barceloneta
$ cd src/plonetheme/tester/theme
```

The `package.json` still has `"@plone/plonetheme-barceloneta-base": "^3.0.0b6"`.  Accept it for now.  Surprisingly to me, building already fails with this version:

```
$ npm install
$ npm run build

> my-theme@1.0.0 build
> npm-run-all css-compile-main css-prefix-main css-minify-main


> my-theme@1.0.0 css-compile-main
> sass --load-path=node_modules --style expanded --source-map --embed-sources --no-error-css styles/theme.scss:styles/theme.css

Error: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  bootstrap/scss/_maps.scss 55:16  @import
  styles/theme.scss 23:9           root stylesheet
ERROR: "css-compile-main" exited with 65.
```

So it would seem that with the Bootstrap 5.3 available on npmjs.org, our training documentation is broken.

Okay, let's use the latest [barceloneta-base tag from npm](https://www.npmjs.com/package/@plone/plonetheme-barceloneta-base?activeTab=versions).  Hey, why is this `3.1.0-alpha.1` and not 3.1.3?

Oh well, let's go with the alpha then.  `npm install && npm run build`... Same error.

Try `git+https://github.com/plone/plonetheme.barceloneta.git#3.1.3` as version then.  Install and build, same error.

Take over the `devDependencies` from [3.1.3 package.json](https://github.com/plone/plonetheme.barceloneta/blob/3.1.3/package.json#L25-L36).  The only changes that pull in new major versions are this:

```
-    "postcss-cli": "^9.0.1",
+    "postcss-cli": "^10.1.0",
+    "stylelint": "^14.16.1",
-    "stylelint-config-twbs-bootstrap": "^5.0.0",
+    "stylelint-config-twbs-bootstrap": "^7.0.0",
```

Install and run build, same error.

The Barceloneta `package.json` has a `bootstrap` pin, which is not in the `package.json` that you get from `plonecli`.  Let's add it: "5.3.0".  Install and run build: same error.

So how do I build a new theme?  Do we need an update in [`bobtemplates.plone`](https://github.com/plone/bobtemplates.plone)?

So for clarity, my `package.json` is now this:

```
{
  "//": "Put here only theme dependencies, devDependencies should stay outside of the theme folder in the package root.",
  "name": "my-theme",
  "version": "1.0.0",
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "clean-css-cli": "^5.6.2",
    "nodemon": "^2.0.21",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.21",
    "postcss-cli": "^10.1.0",
    "sass": "^1.58.3",
    "stylelint": "^14.16.1",
    "stylelint-config-twbs-bootstrap": "^7.0.0",
    "tinymce": "^5.10.7"
  },
  "scripts": {
    "watch": "nodemon --watch styles/ --ext scss --exec \"npm run css-main\"",
    "build": "npm-run-all css-compile-main css-prefix-main css-minify-main",
    "css-main": "npm-run-all css-compile-main css-prefix-main css-minify-main",
    "css-compile-main": "sass --load-path=node_modules --style expanded --source-map --embed-sources --no-error-css styles/theme.scss:styles/theme.css",
    "css-prefix-main": "postcss --config postcss.config.js --replace \"styles/*.css\" \"!styles/*.min.css\"",
    "css-minify-main": "cleancss -O1 --format breakWith=lf --with-rebase --source-map --source-map-inline-sources --output styles/theme.min.css styles/theme.css",
    "css-lint": "stylelint \"styles/**/*.scss\" --cache --cache-location .cache/.stylelintcache"
  },
  "dependencies": {
    "bootstrap": "5.3.0",
    "@plone/plonetheme-barceloneta-base": "git+https://github.com/plone/plonetheme.barceloneta.git#3.1.3"
  }
}
```

And the output from fresh:

```
$ rm -rf node_modules/ package-lock.json
$ node --version
v18.16.0
$ npm --version
9.5.1
$ npm install

added 311 packages, and audited 312 packages in 9s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run build

> my-theme@1.0.0 build
> npm-run-all css-compile-main css-prefix-main css-minify-main


> my-theme@1.0.0 css-compile-main
> sass --load-path=node_modules --style expanded --source-map --embed-sources --no-error-css styles/theme.scss:styles/theme.css

Error: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  bootstrap/scss/_maps.scss 55:16  @import
  styles/theme.scss 23:9           root stylesheet
ERROR: "css-compile-main" exited with 65.
```

Wait a minute.  Why does my unchanged custom theme work, and an almost similar new theme not?  Aha, when I remove the `node_modules` **and** `package-lock.json` it fails in the existing theme as well.  Solution there: add `"bootstrap": "5.2.3"` to the `dependencies`.  With the original `package.json` from `bobtemplates.plone` this change works too.  It does not seem to matter at first glance whether I put this in `dependencies` or `devDependencies`.

But that does not help when you want to use latest Barceloneta and Bootstrap 5.3.0.

**Comment by petschki** [comment]
I've fixed that in bobtemplates `theme_barceloneta` skeleton ... though for custom themes, these changes have to be made by hand in the generated theme. See this commit: https://github.com/plone/bobtemplates.plone/pull/550/commits/e61c34439582eac2b52fab15327c849a69e6da05 ... there should be an upgrade note somewhere but I do not know right now where to place this... barceloneta? bobtemplates? plone docs?

**Comment by mauritsvanrees** [comment]
Your PR fixes it, thanks!  See notes there.
