### ISSUE TITLE
Strange layout behaviour when resizing between mobile and desktop layouts

### ISSUE THREAD

**Issue by chrismilway** [plone/plonetheme.barceloneta#35]
(As a logged in user) if the window is resized from below the 768px breakpoint to above it, the padding applied to the left of the body element is applied incorrectly – it appears to be double the width it needs to be to clear the toolbar (120px rather than 60px). This pushes the page off the right hand edge of the window between 768px and 888px (e.g. 768 + 120)

There are also some strange behaviour of the flyout menus, which render at the top of the window rather than lining up with the menu entry after the same layout transition.

**Comment by vangheem** [comment]
Are you reloading the page or just manually resizing the browser window?

**Comment by chrismilway** [comment]
manually resizing the browser

**Comment by chrismilway** [comment]
If the page is then refreshed the layout is fixed. 

should say my testing has been in FF 39.0 and Chrome 43.0 on Mac

**Comment by vangheem** [comment]
Okay. It's a toolbar artifact. Not sure I'd classify it as a bug. Resizing windows is something only developers do. It'd be nice if toolbar would follow the resize window events well enough to re-apply itself on change but I'd probably just close this ticket. It's also not a barceloneta bug.

**Comment by chrismilway** [comment]
Fair enough on it not being a barceloneta bug, but I don't buy you dismisal of this being a developer-only problem. In my experience of user testing content editor frequently resize windows when they're dealing with multiple windows and software.

**Comment by vangheem** [comment]
Okay, please put a bug: https://github.com/plone/Products.CMFPlone for toolbar issues on resizing.

**Comment by allcaps** [comment]
There is an issue for this in Products.CMFPlone. See https://github.com/plone/Products.CMFPlone/issues/1127
