### ISSUE TITLE
Avoid mixing CSS and XPath selectors on Diazo rules

### ISSUE THREAD

**Issue by davilima6** [plone/plonetheme.barceloneta#38]
Convert all or most unneccessary XPATHs to CSS so code is more homogeneous and at least with Vanilla Plone there's one less thing to learn.

The only place they *might* be needed is [inside the `test` attribute of the  `<xsl:if>` tags](https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/rules.xml#L47-L50).

**Comment by pbauer** [comment]
:+1: Having neither xpath nor xslt in barceloneta would be good for beginners. I doubt it's possible.

**Comment by davilima6** [comment]
Agree, probably not possible. My point is we can get closer to it, I mean: #39

**Comment by sneridagh** [comment]
+1 for me too. Whatever we do to simplify code for beginners is always fine.
