### ISSUE TITLE
When using barceloneta only for the backend, none of the toolbar submenus pop out

### ISSUE THREAD

**Issue by fulv** [plone/plonetheme.barceloneta#64]
If one follows the documentation for **Using the barceloneta theme only for the backend** in a custom Diazo theme (http://docs.plone.org/adapt-and-extend/theming/barceloneta.html#using-the-barceloneta-theme-only-for-the-backend), clicking any of the toolbar items that have submenus (e.g. Add, Display, Workflow, Manage Portlets, Admin) results in loading a new page at the URL corresponding to the static version of the submenu.

For example, the _admin_ item in the toolbar (at the bottom) results in the URL http://localhost:8080/yoursite/useractions being loaded.  

With normal Barceloneta, when one clicks the _admin_ item, a  popup menu with the items _Preferences_, _Site Setup_ and _Logout_ appears.

I'd like the same submenus to display even with my custom theme.

**Comment by fulv** [comment]
It looks like the documentation is wrong, because the issue is caused by a duplication of the `<div id="edit-zone" role="toolbar" class="pat-toolbar initialized">` element.

If I remove this, the `div#edit-zone` is no longer duplicated (but still exists), so everything works:

```
    <!-- Insert the toolbar -->
    <before
        css:theme-children="body"
        css:content-children="#edit-bar"
        css:if-not-content=".ajax_load"
        css:if-content=".userrole-authenticated"
        />
```

Can someone please confirm this?  I will then fix the docs.

**Comment by djay** [comment]
Yes, the backend.cfg was built to insert your edit bar regardless of themed or unthemed so the documentation is wrong.
Not sure if that was the right choice or not since it’s possible you might decide not to use the conditon css:if-content=“.userrole-authenticated” to determine if the edit bar should appear or not.

**Comment by fulv** [comment]
Also, adding these rules from the docs causes a scary-looking error in the js console, whereas leaving them out does not seem to have any ill effect:

```
    <!-- Include basic plone/toolbar bundles -->
    <after
        css:theme-children="head"
        css:content="head link[data-bundle='basic'], head link[data-bundle='plone'], head link[data-bundle='plone-logged-in'], head link[data-bundle='diazo']"
        />
    <after
        css:theme-children="head"
        css:content="head script[data-bundle='basic'], head script[data-bundle='plone'], head script[data-bundle='plone-logged-in'], script link[data-bundle='diazo']"
        />
```
