### ISSUE TITLE
Use the new Roboto

### ISSUE THREAD

**Issue by allcaps** [plone/plonetheme.barceloneta#73]
The Roboto version shipped with Barceloneta is the old Roboto. In 2014 a new, improved Roboto was released. Should we ship the new one?

http://www.fontsquirrel.com/fonts/roboto
http://www.fontsquirrel.com/fonts/roboto-2014

Old:
------
![screen shot 2015-12-27 at 20 32 01](https://cloud.githubusercontent.com/assets/1969342/12025842/187b3828-adb3-11e5-839d-bb22f8a0ee19.png)
New:
------
![screen shot 2015-12-27 at 20 33 27](https://cloud.githubusercontent.com/assets/1969342/12025843/187b982c-adb3-11e5-86fd-7b0ee4d4e2f4.png)

Difference of the type faces used in above screenshots:
- The old `K` has a typical horizontal bar. The new Roboto uses a more traditional (and less dissonant) glyph shape.
- The ascenders and descenders of the new Roboto are smaller. Or the x height is relatively increased.  This is considered more legible.
- The italics seem more balanced, same greyness as the regular text. 
- The new Roboto runs more economically. Glyphs have less width. (Most obvious in line length of footer text and the wrapping of the text in the left portlet)
- `<` and `>` and bullets have better horizontal alignment.

I think the new Roboto is more legible and better balanced and should be supplied with Barceloneta.

**Comment by gforcada** [comment]
:+1: for what is worth

**Comment by vangheem** [comment]
+1
