### ISSUE TITLE
Problem with copying barceloneta

### ISSUE THREAD

**Issue by sandrarum** [plone/plonetheme.barceloneta#94]
For editing the Barceloneta theme and changing some colors, I tried to copy it. But I can't open the TTW-Editor for the copied Theme.

As you can see in the pictures there are some problems with the patterns and getting the resources.

![bildschirmfotoproblembarceloneta](https://cloud.githubusercontent.com/assets/3244630/13810424/0d9ba76c-eb70-11e5-9aee-a1764198d116.png)

**Comment by acsr** [comment]
There is a bug with the Diazo theme editor in Plone 5.0.2 that fails to load the filemanager pattern. Pin plone.app.theming = 1.2.18 in the version cfg of your buildout.cfg or version.cfg and the theme editor starts working. Make sure to remove the pin after updating Plone.
see 
* https://github.com/plone/Products.CMFPlone/issues/1316
* https://github.com/plone/plone.app.theming/blob/master/CHANGES.rst
